name: CI

on: [push]

jobs:
  sniff:
    name: ğŸ•µï¸ PHP ${{ matrix.php-version }} Code Sniffer
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: âš™ï¸ Install composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}
      - name: ğŸ•µï¸ Run Code Sniffer
        run: ./vendor/bin/phpcs -vvv

  analyze:
    name: ğŸ” PHP ${{ matrix.php-version }} Static Analysis
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: âš™ï¸ Install composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}
      - name: ğŸ” Perform Static Analysis
        run: ./vendor/bin/phpstan -vvv

  test:
    name: ğŸ§ª PHP ${{ matrix.php-version }} Unit Testing
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: âš™ï¸ Install composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}
      - name: ğŸ§ª Run Tests
        run: ./vendor/bin/phpunit -vvv
