name: CI

on: [push]

jobs:
  sniff:
    name: Sniff on PHP ${{ matrix.php-version }}
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: âš™ï¸ Install composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}
      - name: ğŸ•µï¸ Code Sniffer
        run: ./vendor/bin/phpcs -vvv

  analyze:
    name: Analyze on PHP ${{ matrix.php-version }}
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: âš™ï¸ Install composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}
      - name: ğŸ” Static Analysis
        run: ./vendor/bin/phpstan -vvv

  test:
    name: Test on PHP ${{ matrix.php-version }}
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: âš™ï¸ Install composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}
      - name: ğŸ§ª Unit Tests
        run: ./vendor/bin/phpunit -vvv
