name: Test in Docker

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Checkout Repo
        uses: actions/checkout@v2
      - name: ğŸ³ Build Container
        run: docker-compose build
      - name: ğŸ§ª Test in Docker
        run: docker-compose up
